import {
  Braces,
  Clock,
  Binary,
  Link,
  Fingerprint,
  KeyRound,
  Hash,
  FileText,
  Palette,
  QrCode,
  Shield,
  Sparkles,
  Image,
  FileCode,
  FileJson,
  Globe,
  Terminal,
  Paintbrush,
  Send,
  Container,
  FileDown,
  FileSpreadsheet,
  GitCompare,
  Brain,
  Wand2,
  FileStack,
  Ruler,
  Timer,
  FileDiff,
  BookOpen,
  Database,
  ArrowRightLeft,
  Network,
  ShieldCheck,
  FileSearch,
  CaseSensitive,
  FileUp,
  Archive,
  Smartphone,
  type LucideIcon,
} from 'lucide-react';

export interface ToolItem {
  id: string;
  name: string;
  description: string;
  path: string;
  icon: LucideIcon;
  category: string;
  keywords: string[];
}

export const toolCategories = [
  { id: 'format', name: '格式化' },
  { id: 'encode', name: '编解码' },
  { id: 'generate', name: '生成器' },
  { id: 'utility', name: '实用工具' },
  { id: 'advanced', name: '高级工具' },
  { id: 'network', name: '网络与高阶' },
  { id: 'ai-misc', name: 'AI 与杂项' },
  { id: 'extension', name: '扩展工具' },
] as const;

export const tools: ToolItem[] = [
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: '格式化、压缩和验证 JSON 数据',
    path: '/tools/json-formatter',
    icon: Braces,
    category: 'format',
    keywords: ['json', 'format', '格式化', '压缩', '验证'],
  },
  {
    id: 'timestamp',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期时间互转',
    path: '/tools/timestamp',
    icon: Clock,
    category: 'utility',
    keywords: ['timestamp', '时间戳', '日期', 'unix', 'dayjs'],
  },
  {
    id: 'base64',
    name: 'Base64 编解码',
    description: '文本 Base64 编码与解码，支持 Unicode',
    path: '/tools/base64',
    icon: Binary,
    category: 'encode',
    keywords: ['base64', '编码', '解码', 'btoa', 'atob'],
  },
  {
    id: 'url-encoder',
    name: 'URL 编解码',
    description: 'URL 编码与解码',
    path: '/tools/url-encoder',
    icon: Link,
    category: 'encode',
    keywords: ['url', 'encode', 'decode', '编码', '解码'],
  },
  {
    id: 'uuid',
    name: 'UUID 生成器',
    description: '生成 UUID v4，支持批量生成',
    path: '/tools/uuid',
    icon: Fingerprint,
    category: 'generate',
    keywords: ['uuid', 'guid', '生成', '唯一标识'],
  },
  {
    id: 'password',
    name: '密码生成器',
    description: '自定义规则生成安全密码',
    path: '/tools/password',
    icon: KeyRound,
    category: 'generate',
    keywords: ['password', '密码', '生成', '安全'],
  },
  {
    id: 'hash',
    name: '哈希计算器',
    description: '计算 MD5、SHA-1、SHA-256 哈希值',
    path: '/tools/hash',
    icon: Hash,
    category: 'utility',
    keywords: ['hash', 'md5', 'sha', '哈希', '加密'],
  },
  {
    id: 'word-counter',
    name: '字数统计',
    description: '统计字符、单词、行数和段落数',
    path: '/tools/word-counter',
    icon: FileText,
    category: 'utility',
    keywords: ['word', 'count', '字数', '统计', '字符'],
  },
  {
    id: 'color',
    name: '颜色转换器',
    description: 'HEX、RGB、HSL 颜色格式互转',
    path: '/tools/color',
    icon: Palette,
    category: 'utility',
    keywords: ['color', 'hex', 'rgb', 'hsl', '颜色'],
  },
  {
    id: 'qrcode',
    name: '二维码生成',
    description: '将文本或 URL 生成二维码图片',
    path: '/tools/qrcode',
    icon: QrCode,
    category: 'generate',
    keywords: ['qr', 'qrcode', '二维码', '生成'],
  },
  {
    id: 'jwt-parser',
    name: 'JWT 解析器',
    description: '解码 JWT Token 的 Header、Payload 和 Signature',
    path: '/tools/jwt-parser',
    icon: Shield,
    category: 'advanced',
    keywords: ['jwt', 'token', '解析', 'decode', 'payload'],
  },
  {
    id: 'code-beautifier',
    name: '代码美化器',
    description: '使用 Prettier 格式化 JavaScript、CSS、HTML、JSON 代码',
    path: '/tools/code-beautifier',
    icon: Sparkles,
    category: 'advanced',
    keywords: ['prettier', 'format', 'beautify', '格式化', '代码'],
  },
  {
    id: 'image-processor',
    name: '图片压缩转换',
    description: '图片压缩、格式转换和尺寸调整',
    path: '/tools/image-processor',
    icon: Image,
    category: 'advanced',
    keywords: ['image', 'compress', '图片', '压缩', 'webp', 'png'],
  },
  {
    id: 'yaml-converter',
    name: 'YAML 转换器',
    description: 'YAML 与 JSON 格式双向转换',
    path: '/tools/yaml-converter',
    icon: FileCode,
    category: 'advanced',
    keywords: ['yaml', 'json', '转换', 'yml'],
  },
  {
    id: 'xml-converter',
    name: 'XML 转换器',
    description: 'XML 与 JSON 格式双向转换',
    path: '/tools/xml-converter',
    icon: FileJson,
    category: 'advanced',
    keywords: ['xml', 'json', '转换', 'parse'],
  },
  {
    id: 'network-query',
    name: '网络查询',
    description: 'IP 地址查询与 DNS 记录解析',
    path: '/tools/network-query',
    icon: Globe,
    category: 'advanced',
    keywords: ['ip', 'dns', 'network', '网络', '域名'],
  },
  {
    id: 'chmod-calculator',
    name: 'chmod 计算器',
    description: '符号权限与数字权限双向转换',
    path: '/tools/chmod-calculator',
    icon: Terminal,
    category: 'advanced',
    keywords: ['chmod', 'permission', '权限', 'unix', 'linux'],
  },
  {
    id: 'css-generator',
    name: 'CSS 生成器',
    description: '可视化生成 Box Shadow 和 Border Radius CSS',
    path: '/tools/css-generator',
    icon: Paintbrush,
    category: 'advanced',
    keywords: ['css', 'shadow', 'radius', 'box-shadow', 'border-radius'],
  },
  {
    id: 'api-tester',
    name: 'API 测试器',
    description: '类似 Postman 的 HTTP 请求调试工具',
    path: '/tools/api-tester',
    icon: Send,
    category: 'network',
    keywords: ['api', 'http', 'postman', 'request', 'axios'],
  },
  {
    id: 'docker-converter',
    name: 'Docker 转换',
    description: '将 docker run 命令转换为 docker-compose.yml',
    path: '/tools/docker-converter',
    icon: Container,
    category: 'network',
    keywords: ['docker', 'compose', 'container', 'run'],
  },
  {
    id: 'html-to-pdf',
    name: 'HTML 转 PDF',
    description: '将 HTML 代码渲染为 PDF 并预览下载',
    path: '/tools/html-to-pdf',
    icon: FileDown,
    category: 'network',
    keywords: ['html', 'pdf', 'export', 'print'],
  },
  {
    id: 'excel-converter',
    name: 'Excel 转换',
    description: 'CSV/Excel 与 JSON 格式双向转换',
    path: '/tools/excel-converter',
    icon: FileSpreadsheet,
    category: 'network',
    keywords: ['excel', 'csv', 'xlsx', 'json', 'sheet'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    description: '对比两个 JSON 文档的差异',
    path: '/tools/json-diff',
    icon: GitCompare,
    category: 'network',
    keywords: ['json', 'diff', 'compare', '对比'],
  },
  {
    id: 'ai-code-explainer',
    name: 'AI 代码解释',
    description: '使用 AI 详细解释代码逻辑并提供优化建议',
    path: '/tools/ai-code-explainer',
    icon: Brain,
    category: 'ai-misc',
    keywords: ['ai', 'code', 'explain', 'openai', '解释'],
  },
  {
    id: 'ai-regex-generator',
    name: 'AI 正则生成',
    description: '用自然语言描述需求，AI 生成正则表达式',
    path: '/tools/ai-regex-generator',
    icon: Wand2,
    category: 'ai-misc',
    keywords: ['ai', 'regex', 'regular', 'expression', '正则'],
  },
  {
    id: 'dev-templates',
    name: '开发模板',
    description: '快速生成 .gitignore、README 和 LICENSE',
    path: '/tools/dev-templates',
    icon: FileStack,
    category: 'ai-misc',
    keywords: ['gitignore', 'readme', 'license', 'template'],
  },
  {
    id: 'unit-converter',
    name: '单位换算',
    description: '进制、存储、CSS 单位和宽高比换算',
    path: '/tools/unit-converter',
    icon: Ruler,
    category: 'ai-misc',
    keywords: ['unit', 'convert', 'radix', 'storage', 'css'],
  },
  {
    id: 'pomodoro-lorem',
    name: '番茄钟 & Lorem',
    description: '专注计时器与 Lorem Ipsum 占位文本生成',
    path: '/tools/pomodoro-lorem',
    icon: Timer,
    category: 'ai-misc',
    keywords: ['pomodoro', 'timer', 'lorem', 'ipsum', '番茄钟'],
  },
  {
    id: 'text-diff',
    name: '文本差异对比',
    description: '对比两段文本的差异，高亮新增、删除与修改',
    path: '/tools/text-diff',
    icon: FileDiff,
    category: 'extension',
    keywords: ['text', 'diff', 'compare', '文本', '对比', '差异'],
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 预览',
    description: 'Markdown 实时预览编辑器，支持 GFM 语法与代码高亮',
    path: '/tools/markdown-preview',
    icon: BookOpen,
    category: 'extension',
    keywords: ['markdown', 'preview', 'gfm', '预览', '编辑器'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL 格式化',
    description: '美化或压缩 SQL 语句，支持多种数据库方言',
    path: '/tools/sql-formatter',
    icon: Database,
    category: 'extension',
    keywords: ['sql', 'format', 'mysql', 'postgresql', '格式化'],
  },
  {
    id: 'curl-converter',
    name: 'cURL 转换器',
    description: '将 cURL 命令转换为 Python、JavaScript、Java 等语言代码',
    path: '/tools/curl-converter',
    icon: ArrowRightLeft,
    category: 'extension',
    keywords: ['curl', 'converter', 'python', 'javascript', 'requests', 'fetch'],
  },
  {
    id: 'subnet-calculator',
    name: 'IP 子网计算',
    description: '计算网络地址、广播地址、可用 IP 范围与子网掩码',
    path: '/tools/subnet-calculator',
    icon: Network,
    category: 'extension',
    keywords: ['ip', 'subnet', 'cidr', 'network', '子网', '掩码'],
  },
  {
    id: 'password-strength',
    name: '密码强度检测',
    description: '实时评估密码强度，提供破解时间估算与安全建议',
    path: '/tools/password-strength',
    icon: ShieldCheck,
    category: 'extension',
    keywords: ['password', 'strength', 'zxcvbn', '密码', '强度', '安全'],
  },
  {
    id: 'json-schema',
    name: 'JSON Schema 生成',
    description: '从 JSON 数据自动推断并生成 JSON Schema',
    path: '/tools/json-schema',
    icon: FileSearch,
    category: 'extension',
    keywords: ['json', 'schema', 'generator', 'draft', '推断'],
  },
  {
    id: 'naming-converter',
    name: '命名风格转换',
    description: 'camelCase、snake_case、kebab-case 等命名风格互转',
    path: '/tools/naming-converter',
    icon: CaseSensitive,
    category: 'extension',
    keywords: ['naming', 'camelCase', 'snake_case', 'kebab-case', '命名', '转换'],
  },
  {
    id: 'base64-file',
    name: 'Base64 文件编解码',
    description: '文件与 Base64 字符串互转，支持图片、PDF、文本等',
    path: '/tools/base64-file',
    icon: FileUp,
    category: 'extension',
    keywords: ['base64', 'file', 'encode', 'decode', '文件', '编解码'],
  },
  {
    id: 'gzip-tool',
    name: 'GZip 压缩/解压',
    description: '使用浏览器原生 API 进行 GZip 压缩与解压，支持 .zip 解压',
    path: '/tools/gzip-tool',
    icon: Archive,
    category: 'extension',
    keywords: ['gzip', 'compress', 'decompress', '压缩', '解压', 'base64'],
  },
  {
    id: 'splash-generator',
    name: '手机启动图制作',
    description: '一键生成 iOS / Android 各尺寸启动图，支持批量下载',
    path: '/tools/splash-generator',
    icon: Smartphone,
    category: 'extension',
    keywords: ['splash', 'startup', 'ios', 'android', '启动图', '闪屏'],
  },
];

export function getToolsByCategory() {
  return toolCategories.map((cat) => ({
    ...cat,
    tools: tools.filter((t) => t.category === cat.id),
  }));
}

export function searchTools(query: string): ToolItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return tools;
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.toLowerCase().includes(q))
  );
}
